# GoReleaser configuration
# Documentation: https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...
    # Generate manual pages for distribution
    - mkdir -p man
    - go run main.go manual --output ./man

builds:
  - id: vapi
    main: ./main.go
    binary: vapi
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
    ldflags:
      - -s -w -X main.buildVersion={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser

archives:
  - id: vapi
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    wrap_in_directory: false
    files:
      - README.md
      - LICENSE
      - man/*.1

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: Bug fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: VapiAI
    name: cli
  name_template: "{{.ProjectName}}-v{{.Version}}"
  header: |
    ## Vapi CLI v{{.Version}}
    
    Welcome to the v{{.Version}} release of Vapi CLI!
    
    ### Installation
    
    #### Unix/Linux/macOS
    ```bash
    curl -sSL https://vapi.ai/install.sh | bash
    ```
    
    #### Windows
    ```powershell
    iex ((New-Object System.Net.WebClient).DownloadString('https://vapi.ai/install.ps1'))
    ```
    
    #### Docker
    ```bash
    docker run -it ghcr.io/vapiai/cli:latest --help
    ```
    
    #### Manual Download
    ```bash
    curl -sSL https://github.com/VapiAI/cli/releases/download/v{{.Version}}/cli_$(uname -s)_$(uname -m).tar.gz | tar xz
    sudo mv vapi /usr/local/bin
    ```
    
  footer: |
    **Full Changelog**: https://github.com/VapiAI/cli/compare/{{ .PreviousTag }}...{{ .Tag }}
    
    ---
    
    _Built with ❤️ by the Vapi team_

# Package managers removed - using install scripts instead

# Docker images (containerized usage)
dockers:
  - image_templates:
      - "ghcr.io/vapiai/cli:{{ .Tag }}"
      - "ghcr.io/vapiai/cli:v{{ .Major }}"
      - "ghcr.io/vapiai/cli:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/vapiai/cli:latest"
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    skip_push: false

# Announce releases
announce:
  slack:
    enabled: true
    message_template: |
      🚀 **Vapi CLI {{.Tag}} Released!**
      
      📦 **Installation:**
      • Unix/Linux/macOS: `curl -sSL https://vapi.ai/install.sh | bash`
      • Windows: `iex ((New-Object System.Net.WebClient).DownloadString('https://vapi.ai/install.ps1'))`
      • Docker: `docker run -it ghcr.io/vapiai/cli:{{.Tag}} --help`
      
      🔗 **Links:**
      • Release: {{ .ReleaseURL }}
      • Changelog: {{ .ReleaseURL }}#changelog
    username: "Vapi Release Bot"
    icon_emoji: ":rocket:"
    channel: "#releases"  # or whatever channel you want
    
  discord:
    enabled: false  # Enable when Discord webhook is set up
    message_template: |
      **Vapi CLI {{.Tag}} is out!** 🎉
      
      Check it out at {{ .ReleaseURL }}
    
  twitter:
    enabled: false  # Enable when Twitter credentials are set up
    message_template: |
      Vapi CLI {{.Tag}} is out! 🚀
      
      Check it out at {{ .ReleaseURL }}
      
      #VapiAI #DevTools #CLI 