# This workflow is intentionally disabled
#
# The install.sh script changes infrequently, so manual updates are preferred.
#
# To update install.sh on vapi.ai:
# 1. Copy scripts/install.sh to your website repo's public/ directory
# 2. Commit and push to trigger Vercel deployment
#
# If you want to automate this in the future, see DISTRIBUTION_SETUP.md

name: Deploy Install Script

on:
  push:
    branches: [main]
    paths:
      - "scripts/install.sh"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CLI repo
        uses: actions/checkout@v4

      # Option 1: Direct push to website repo (Automated, but use with caution)
      - name: Push to Website Repository
        env:
          WEBSITE_REPO_TOKEN: ${{ secrets.WEBSITE_REPO_TOKEN }}
        run: |
          # Clone website repo
          git clone https://${WEBSITE_REPO_TOKEN}@github.com/VapiAI/website.git website-repo

          # Copy install script to public directory (adjust path as needed)
          cp scripts/install.sh website-repo/public/install.sh

          # Configure git
          cd website-repo
          git config user.name "Vapi CLI Bot"
          git config user.email "cli-bot@vapi.ai"

          # Commit and push if there are changes
          if git diff --quiet; then
            echo "No changes to install.sh"
          else
            git add public/install.sh
            git commit -m "chore: update install.sh from CLI repo

          Source: https://github.com/VapiAI/cli/commit/${{ github.sha }}"
            git push origin main
          fi

      # Option 2: Vercel Deploy Hook (Trigger rebuild)
      # - name: Trigger Vercel Deploy
      #   run: |
      #     curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK }}

      # Option 3: Create PR with auto-merge (Safer than direct push)
      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v5
      #   with:
      #     token: ${{ secrets.WEBSITE_REPO_TOKEN }}
      #     repository: VapiAI/website
      #     path: website
      #     commit-message: 'chore: update install.sh from CLI repo'
      #     title: '[Automated] Update CLI install script'
      #     body: |
      #       This PR updates the CLI install script from the latest version in the CLI repository.
      #
      #       Source: https://github.com/VapiAI/cli/commit/${{ github.sha }}
      #
      #       Auto-merge enabled if all checks pass.
      #     branch: update-cli-install-script
      #     delete-branch: true
      #     labels: |
      #       automated
      #       cli-update

      # Option 4: Vercel API Deployment (if you set up an API endpoint)
      # - name: Deploy via Vercel API
      #   run: |
      #     # This would require setting up an API endpoint in your Vercel app
      #     # that accepts the file content and writes it to the public directory
      #     curl -X POST https://vapi.ai/api/deploy-file \
      #       -H "Authorization: Bearer ${{ secrets.VAPI_DEPLOY_TOKEN }}" \
      #       -H "Content-Type: application/json" \
      #       -d @- << EOF
      #     {
      #       "path": "/install.sh",
      #       "content": $(cat scripts/install.sh | jq -Rs .),
      #       "source": "cli-repo"
      #     }
      #     EOF
